### ISSUE TITLE
Convert PAR/REC to Nifti 

### ISSUE THREAD

**Issue by SiriusHou** [rordenlab/MRIcroGL12#19]
I downloaded MRIcroGL 2-Novemember from https://www.nitrc.org/projects/mricrogl to convert PAR/REC file into Nifti format. Now, I got stuck with a problem. When I tried to convert a PAR/REC file into Nifti format, the MRIcroGL doesn't work. The error message is as below.
![image](https://user-images.githubusercontent.com/20582047/101793716-197c8200-3ad4-11eb-8613-8e6c9733975b.png)

However, if I modify the diffusion (ap, fh, rl) parameter in image information session from (0.000, 0.000, -1.000) to (0.000001, 0.000, -1.000), MRIcroGL could convert the data into Nifti format. Can you help me fix the problem?
![image](https://user-images.githubusercontent.com/20582047/101793606-fb168680-3ad3-11eb-9a59-9c2ca2749a92.png)

**Comment by neurolabusc** [comment]
See my comments for [dcm2niix issue 461](https://github.com/rordenlab/dcm2niix/issues/461). If you can share an image via GoogleDrive/Box/etc (send link to email in my avatar) I can provide feedback. Otherwise, feel free to modify the dcm2niix code and generate a pull request. I do not have access to Philips equipment, so my support for this format is limited.

**Comment by SiriusHou** [comment]
Thank you for your rapid reply. I will try your suggestion to see if I can work around. Thanks a lot!

**Comment by neurolabusc** [comment]
@SiriusHou I have moved this issue to [dcm2niix](https://github.com/rordenlab/dcm2niix/issues/462). Can you download the latest build from AppVeyor and see if replacing the copy of dcm2niix in you \MRIcroGL\Resources folder with the latest commit resolves your issue? Thanks!

**Comment by SiriusHou** [comment]
The problem is fixed! Thank you!
