### ISSUE TITLE
Nifti Image loading fails if the file path contains /atlases/

### ISSUE THREAD

**Issue by CGSchwarzMayo** [rordenlab/MRIcroGL12#7]
Version 1.2.20190902+
Tested in both windows and linux release builds.

Attempting to open any nifti image I have lying around will fail (pixelated image and color scale locked to rainbow) if the directory path contains the string /atlases/
![image](https://user-images.githubusercontent.com/38332171/65695985-1a93d180-e03e-11e9-8542-703cd4d60900.png)

The /atlases/ string can occur anywhere in the file path, as far as I can tell, to trigger the bug. /home/user/atlases/foo.nii triggers it just the same as /home/user/foo/bar/atlases/foo.nii

Directories named atlases_ etc. are fine. It seems to be specific to /atlases/.

This issue did not occur on 1.1x builds.

Thank you! Please let me know if I can be of further help.

**Comment by neurolabusc** [comment]
A feature of MRIcroGL 1.2 is that it will load a NIfTI image as a labeled map, using the FSL random color scheme and nearest neighbor interpolation if it is in a folder named "Atlases" a good example are the "Resources/Atlases" images provided with the software. In the past, one had to set the NIfTI intention, which frustrated many users. I will evaluate whether to retain this feature for future releases, but for the moment use "Atlases" folders to store labeled maps where nearest neighbor interpolation is expected (e.g. a region where area 17 and 19 meet should always appear to be one of these regions, not area 18).

**Comment by CGSchwarzMayo** [comment]
Thanks for your explanation. I'm not sure I like the behavior that the name of the file path causes it to be loaded differently, but I can understand where this could be at least more transparent to users than nifti intent codes. Perhaps there could be an option to manually change the interpolation and random scheme if the default "guess" based on name/path was not what the user wanted?

Part of what confused me here from understanding that this was intended behavior is I think I have stumbled upon a related bug that the NN interpolation is not working correctly for 32-bit datatypes. 

My example is: MCALT_ADIR122.nii (available publicly here: https://www.nitrc.org/projects/mcalt/)
It's a 32 bpp float but all the values are integers.

In a non-atlases folder:
![image](https://user-images.githubusercontent.com/38332171/65704001-5e410800-e04b-11e9-959a-537f4c15acb9.png)

In an atlases folder:
![image](https://user-images.githubusercontent.com/38332171/65704105-89c3f280-e04b-11e9-885e-a87175b02cb8.png)

I get the same incorrect result if I convert it to (32-bit, signed) int:
fslmaths MCALT_ADIR122.nii MCALT_ADIR122_int.nii -odt int

It only works properly if I convert to char:
fslmaths MCALT_ADIR122.nii MCALT_ADIR122_char.nii -odt char
![image](https://user-images.githubusercontent.com/38332171/65704264-d27bab80-e04b-11e9-8e3b-a043ff515dae.png)

**Comment by neurolabusc** [comment]
Well spotted. This will be fixed in the next release. I would recommend that atlas label maps be saved as integer rather than floating point images. I like this [page](https://blogs.mathworks.com/cleve/2017/05/08/half-precision-16-bit-floating-point-arithmetic/) on the features of floating point numbers.
  Internally, MRIcroGL natively supports UINT8, INT16 and FLOAT32 datatypes. INT8 is losslessly saved as UINT8 and UINT16 is losslessly saved as INT16. Other datatypes are converted to FLOAT32. This explains why `-odt int` (INT32) behaves the same as FLOAT32 data.
 Since this template only has 122 labels, it should be saved as UINT8 (which can store up to 255 labels, fslmaths refers to this as `-odt char`). For templates with 256-16767 labels on can use INT16 ( fslmaths refers to this as `-odt short`). For Matlab users, [nii_change_datatype.m](https://github.com/rordenlab/spmScripts/blob/master/nii_change_datatype.m). The UINT8 datatype will require 1/4 the disk space and memory of the FLOAT32 and is consequently much faster.

**Comment by CGSchwarzMayo** [comment]
I agree with you that char would be more appropriate for this particular image, and I should probably change the ones in MCALT. But I'm glad that you will fix the NN interpolation for these images in a future release. It may not be ideal but I think it is very common for users to create or encounter such "up-casted" images in the wild.

**Comment by neurolabusc** [comment]
I agree on all points. Just to clarify
 1. MRIcroGL 1.2 will determine that a volume is an labeled atlas rather than a scalar volume if either one of these two attributes is true: 
  a. The image NIfTI intention field is set to `labels`.
  b. The path of the image contains a folder named `atlases`. While this might seem arbitrary, this allows MRIcroGL to automatically detect the FSL atlases (which do not have the NIfTI intention field set).
 2. The issue was not with interpolation, but with assigning a label from the color lookup table to FLOAT32 data. An image loaded as background will always be loaded in its native resolution (without requiring any interpolation) as long the largest dimension is less than the `MaxVox` value set in the advanced preferences (which is 560 by default). Images larger than this will have the dimensions downsampled proportionally so the largest dimension is MaxVox. This downsampling uses a Lanczos filter unless the image is identified as a label, in which case nearest neighbor is used. The downsampling uses the anti-aliasing described by Schumacher in `General Filtered Image Rescaling`.
 3. If an image is determined to be a label map, it will be shown with the FSL random-color color table instead of one of the scalar tables.
